/* Catálogo Distribuidora L y O — 49 productos */
const CATALOG_LYO=[
  {
    "id": "albahaca",
    "name": "Albahaca",
    "categoria": "hierba",
    "unidad_sugerida": "unidad",
    "emoji": "🌿",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/albahaca.png"
  },
  {
    "id": "aguacate",
    "name": "Aguacate",
    "categoria": "fruta",
    "unidad_sugerida": "unidad",
    "emoji": "🥑",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/aguacate.png"
  },
  {
    "id": "ajo",
    "name": "Ajo",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🧄",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/ajo.png"
  },
  {
    "id": "arracacha",
    "name": "Arracacha",
    "categoria": "tuberculo",
    "unidad_sugerida": "kilo",
    "emoji": "🥔",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/arracacha.png"
  },
  {
    "id": "apio",
    "name": "Apio",
    "categoria": "verdura",
    "unidad_sugerida": "unidad",
    "emoji": "🥬",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/apio.png"
  },
  {
    "id": "arveja",
    "name": "Arveja",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🫛",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/arveja.png"
  },
  {
    "id": "banano",
    "name": "Banano",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🍌",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/banano.png"
  },
  {
    "id": "brocoli",
    "name": "Brócoli",
    "categoria": "verdura",
    "unidad_sugerida": "unidad",
    "emoji": "🥦",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/brocoli.png"
  },
  {
    "id": "calabacin",
    "name": "Calabacín",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🥒",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/calabacin.png"
  },
  {
    "id": "cebolla-huevo",
    "name": "Cebolla de Huevo",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🧅",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/cebolla-huevo.png"
  },
  {
    "id": "cebolla-morada",
    "name": "Cebolla morada",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🧅",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/cebolla-morada.png"
  },
  {
    "id": "cebolla-larga",
    "name": "Cebolla Larga",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🧅",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/cebolla-larga.png"
  },
  {
    "id": "cilantro",
    "name": "Cilantro",
    "categoria": "hierba",
    "unidad_sugerida": "unidad",
    "emoji": "🌿",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/cilantro.png"
  },
  {
    "id": "champinones",
    "name": "Champiñones",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🍄",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/champinones.png"
  },
  {
    "id": "espinaca",
    "name": "Espinaca",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🥬",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/espinaca.png"
  },
  {
    "id": "fresa",
    "name": "Fresa",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🍓",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/fresa.png"
  },
  {
    "id": "guayaba",
    "name": "Guayaba",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🍈",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/guayaba.png"
  },
  {
    "id": "granadilla",
    "name": "Granadilla",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🍈",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/granadilla.png"
  },
  {
    "id": "habichuela",
    "name": "Habichuela",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🫘",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/habichuela.png"
  },
  {
    "id": "hierbabuena",
    "name": "Hierba buena",
    "categoria": "hierba",
    "unidad_sugerida": "unidad",
    "emoji": "🌿",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/hierbabuena.png"
  },
  {
    "id": "lechuga-batavia",
    "name": "Lechuga Batavia",
    "categoria": "verdura",
    "unidad_sugerida": "unidad",
    "emoji": "🥬",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/lechuga-batavia.png"
  },
  {
    "id": "lechuga-crespa",
    "name": "Lechuga Crespa",
    "categoria": "verdura",
    "unidad_sugerida": "unidad",
    "emoji": "🥬",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/lechuga-crespa.png"
  },
  {
    "id": "limon",
    "name": "Limón",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🍋",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/limon.png"
  },
  {
    "id": "lulo",
    "name": "Lulo",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🟢",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/lulo.png"
  },
  {
    "id": "mandarina",
    "name": "Mandarina",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🍊",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/mandarina.png"
  },
  {
    "id": "mango",
    "name": "Mango",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🥭",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/mango.png"
  },
  {
    "id": "manzana",
    "name": "Manzana",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🍎",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/manzana.png"
  },
  {
    "id": "maracuya",
    "name": "Maracuyá",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🟡",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/maracuya.png"
  },
  {
    "id": "mazorca",
    "name": "Mazorca",
    "categoria": "verdura",
    "unidad_sugerida": "unidad",
    "emoji": "🌽",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/mazorca.png"
  },
  {
    "id": "melon",
    "name": "Melón",
    "categoria": "fruta",
    "unidad_sugerida": "unidad",
    "emoji": "🍈",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/melon.png"
  },
  {
    "id": "mora",
    "name": "Mora",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🫐",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/mora.png"
  },
  {
    "id": "naranja",
    "name": "Naranja",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🍊",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/naranja.png"
  },
  {
    "id": "papa-criolla",
    "name": "Papa Criolla",
    "categoria": "tuberculo",
    "unidad_sugerida": "kilo",
    "emoji": "🥔",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/papa-criolla.png"
  },
  {
    "id": "papa",
    "name": "Papa",
    "categoria": "tuberculo",
    "unidad_sugerida": "kilo",
    "emoji": "🥔",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/papa.png"
  },
  {
    "id": "papaya",
    "name": "Papaya",
    "categoria": "fruta",
    "unidad_sugerida": "unidad",
    "emoji": "🧡",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/papaya.png"
  },
  {
    "id": "pepino-cohombro",
    "name": "Pepino Cohombro",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🥒",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/pepino-cohombro.png"
  },
  {
    "id": "perejil",
    "name": "Perejil",
    "categoria": "hierba",
    "unidad_sugerida": "unidad",
    "emoji": "🌿",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/perejil.png"
  },
  {
    "id": "pimenton",
    "name": "Pimentón",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🫑",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/pimenton.png"
  },
  {
    "id": "pina",
    "name": "Piña",
    "categoria": "fruta",
    "unidad_sugerida": "unidad",
    "emoji": "🍍",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/pina.png"
  },
  {
    "id": "platano-maduro",
    "name": "Plátano Maduro",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🍌",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/platano-maduro.png"
  },
  {
    "id": "platano-verde",
    "name": "Plátano Verde",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🍌",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/platano-verde.png"
  },
  {
    "id": "remolacha",
    "name": "Remolacha",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🍠",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/remolacha.png"
  },
  {
    "id": "repollo",
    "name": "Repollo",
    "categoria": "verdura",
    "unidad_sugerida": "unidad",
    "emoji": "🥬",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/repollo.png"
  },
  {
    "id": "sandia",
    "name": "Sandía",
    "categoria": "fruta",
    "unidad_sugerida": "unidad",
    "emoji": "🍉",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/sandia.png"
  },
  {
    "id": "tomate-chonto",
    "name": "Tomate Chonto",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🍅",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/tomate-chonto.png"
  },
  {
    "id": "tomate-arbol",
    "name": "Tomate de Árbol",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🍅",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/tomate-arbol.png"
  },
  {
    "id": "tomate-cherry",
    "name": "Tomate Cherry",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🍅",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/tomate-cherry.png"
  },
  {
    "id": "uva",
    "name": "Uva",
    "categoria": "fruta",
    "unidad_sugerida": "kilo",
    "emoji": "🍇",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/uva.png"
  },
  {
    "id": "yuca",
    "name": "Yuca",
    "categoria": "tuberculo",
    "unidad_sugerida": "kilo",
    "emoji": "🥔",
    "tint": "#FFF6D9",
    "edge": "#DDA400",
    "active": true,
    "img": "assets/productos/yuca.png"
  },
  {
    "id": "zanahoria",
    "name": "Zanahoria",
    "categoria": "verdura",
    "unidad_sugerida": "kilo",
    "emoji": "🥕",
    "tint": "#E8F8EE",
    "edge": "#1FA84D",
    "active": true,
    "img": "assets/productos/zanahoria.png"
  }
];
function buildSeedProducts(){return CATALOG_LYO.map(p=>({...p}));}
